version: '3.8'

services: 
  api:
    build: 
      context: .
      dockerfile: common/docker/base-node.dockerfile
    volumes: 
      - '.:/app'
    entrypoint: 'sh -c "npm --prefix services/api install && npm --prefix services/api run start:dev"'
    ports: 
      - 8080:80

  documentation:
    build: 
      context: .
      dockerfile: common/docker/base-node.dockerfile
    volumes: 
      - '.:/app'
    environment: 
      PORT: 80
      API_SERVICE_HOST: api
      API_SERVICE_PORT: 80
    working_dir: /app/services/documentation
    entrypoint: 'sh -c "npm install && npm run dev"'
    ports: 
      - 3000:80

  parser:
    build:
      context: .
      dockerfile: common/docker/base-dotnet.dockerfile
    working_dir: /app/services/parser
    volumes: 
      - '.:/app'
    entrypoint: 'sh -c "dotnet watch run"'
    ports: 
      - 8081:8081
