name: CI

on:
  pull_request:
    branches:
      - cool
    paths:
      - '.github/workflows/ci-api-service.yml'
      - 'common/**'
      - 'services/api/**'

env:
  NODE_VERSION: 14.17.6
  SERVICE: api

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Please
        uses: sagikazarmark/setup-please-action@v0

      - name: Build Services
        run: plz build //services/$SERVICE && plz run //services/$SERVICE